---
platform: linux

inputs:
  - name: build-tar
run:
  path: bash
  args:
    - "-c"
    - |
      apt-get update
      apt-get install -y automake \
      libaspell-dev \
      libc-client2007e-dev \
      libcurl4-openssl-dev \
      libexpat1-dev \
      libgdbm-dev \
      libgmp-dev \
      libjpeg-dev \
      libldap2-dev \
      libmcrypt-dev \
      libmemcached-dev \
      libpng12-dev \
      libpspell-dev \
      libreadline-dev \
      libsasl2-dev \
      libsnmp-dev \
      libsqlite3-dev \
      libssl-dev \
      libzip-dev \
      libdb-dev \
      mercurial \
      snmp-mibs-downloader
      tar xzf build-tar/binary-builder-source.tgz -C /tmp
      cd /tmp/powerpc64le-linux-gnu/ports/php7/*/*/
      yes n | env REPORT_EXIT_STATUS=1 make test
