platform: linux

inputs:
  - name: binary-builder
  - name: buildpacks-ci
params:
  SPEC_TO_RUN:
  RUN_ORACLE_PHP_TESTS: false
  RUBYGEM_MIRROR:
  AWS_ACCESS_KEY:
  AWS_SECRET_ACCESS_KEY:
  EXCLUDE_ON_PPC64LE: false
  BINARY_BUILDER_PLATFORM:
  BINARY_BUILDER_OS_NAME:
run:
  path: buildpacks-ci/tasks/run-binary-builder-integration-specs/run.sh
